### ISSUE TITLE
Expose `state` properties in `AbstractKeyEvent`

### ISSUE THREAD

**Issue by mirka** [rweich/streamdeck-events#14]
I was wondering if we could also expose the `state` and `userDesiredState` [properties](https://developer.elgato.com/documentation/stream-deck/sdk/events-received/#keydown) in the [`AbstractKeyEvent`](https://github.com/rweich/streamdeck-events/blob/main/src/Events/Received/Plugin/AbstractKeyEvent.ts).

These properties are only set for multi-state/multi-action triggers, so maybe they were omitted by accident rather than on purpose. They are necessary bits of information when handling key events for multi-state actions.

(I'm really enjoying your Stream Deck SDK and template by the way. Elgato should make them official 😄)

**Comment by rweich** [comment]
yep, totally missed that.
will take a look into it. just have to figure out how the multistate stuff works first.

thanks for reporting the issue!

**Comment by rweich** [comment]
alright, the properties are exposed now. 👍 
had to change other things as well, as multiactions werent working at all (introducing breaking changes..)
will update the streamdeck-ts package in the next days as well to account for this.
hope this helps

**Comment by mirka** [comment]
Awesome, thanks!
