### ISSUE TITLE
AbstractKeyEvent does not expose Payload Settings

### ISSUE THREAD

**Issue by KazWolfe** [rweich/streamdeck-events#21]
Currently, it appears as though `AbstractKeyEvent` does not expose the `settings` field provided on both `keyDown` and `keyUp` events (existence also referred to [in documentation](https://developer.elgato.com/documentation/stream-deck/sdk/events-received/#keydown)):

```json
{
    "action": "< redacted >",
    "context": "< redacted >",
    "device": "< redacted >",
    "event": "keyDown",
    "payload": {
        "coordinates": {
            "column": 1, 
            "row": 0 
        },
        "isInMultiAction": false,
        "settings": { 
            "key": "value"
        }
    }
}
```

It appears as though `AbstractKeyEvent` should inherit from `AbstractStateEvent`, with the former only adding the extra `userDesiredState` field.

List of exposed fields visible to Rider:

![image](https://user-images.githubusercontent.com/5192145/159113847-e310e710-5780-444f-8aeb-0e9cfa8f29f6.png)

---

Note that there's a very real possibility that this particular issue is being caused by user error as well; if this is the case, just let me know and I'll try to work around this. Alternatively, I'm more than happy to open a PR with the above fix if that's desired instead.

**Comment by rweich** [comment]
Hey there.

Thanks for reporting and the hint for the solution! You're right, its missing from the events.
Should be fixed in 3.1.0
