### ISSUE TITLE
Missing event: `timerUpdate`

### ISSUE THREAD

**Issue by koenbollen** [rweich/streamdeck-events#37]
When setting the member `"TimerInterval": 10000` in the manifest.json, the streamdeck will send the event `timerUpdate` every 10 seconds. This is very useful for timed events, or to refresh some backend data on an interval.

Note: **this is an undocumented feature from the elgato sdk.**

When using your (very nice) framework [rweich/streamdeck-ts](https://github.com/rweich/streamdeck-ts) I get the following error:
```
Error: unknown event: timerUpdate in data: {"event":"timerUpdate"}
    at bv.createByEventPayload (main-o3Cx4NzH.js:8:61621)
    at Ev.createFromPayload (main-o3Cx4NzH.js:8:62389)
    at Wu.createByMessageEvent (main-o3Cx4NzH.js:1:2217)
    at Wu.onMessage (main-o3Cx4NzH.js:1:1831)
```

Could you add this event? (or how could I hack in support for this in the current version?)

Cheers.

**Comment by rweich** [comment]
Heya, thanks for reporting. I'll look into it, but this might take a bit so I hope you're not pressed for time.

**Comment by koenbollen** [comment]
No, that's ok, no rush. 👍🏻 
My plugin was simple enough I got away with a javascript only solution. It would have been a little easier using your library, but I got there without.
Cheers.

**Comment by koenbollen** [comment]
Awesome! Thanks 👍🏻
