### ISSUE TITLE
Missing requried property `isInMultiAction`

### ISSUE THREAD

**Issue by nic96** [rweich/streamdeck-events#42]
I'm getting the following error:
```
Error: error while validating payload: must have required property 'isInMultiAction' payload: {"event":"didReceiveSettings","action":"fun.shiro.counter.action","context":"sd-A00DA431142W9.Default.Keypad.2.0","device":"sd-A00DA431142W9","payload":{"settings":{"count":30,"steps":1},"coordinates":{"row":0,"column":2}}}
```

It may be related to me using opendeck, but for now I've got a local patch applied that makes `isInMultiAction` property optional.

**Comment by rweich** [comment]
Based on the official streamdeck sdk the property should not be optional.
I don't know anything about opendeck, but if you're only getting the error using that, I'm assuming, that the property has to be added there.

**Comment by nic96** [comment]
Alright, that makes sense. I'll close this issue
